### ISSUE TITLE
Project still alive ?

### ISSUE THREAD

**Issue by realgooseman** [veringsek/snap-assist-for-centering#2]
Hi @veringsek,

Just came across this app. I currently use Window Centering Helper but your app could potentially be better.
Is this project still maintained or abandoned ?

**_Some suggestions for the app (if still alive) :_**

- Better color matching for light/dark themes to better fit with the Snap Assist's native colors on Windows 11
- Rounded edges for center snap animation, just like Windows 11's Snap Assist native animations
- Option to show/hide icon from system tray, so it looks like a native Windows integration when hidden
- Option to enable/disable centering active window by the press of a custom key/key combo
- Option to enable/disable auto-centering of new windows the moment they're opened

**_Small bug found :_** 

- When dragging a newly opened window for the first time, it makes the snap animation zoom out even if the cursor is not centered

**Comment by veringsek** [comment]
The rounded corners and the color of Mica effect were actually in my original design, yet I failed to implement those due to my lack of knowledge about that. In fact, it was even a miracle for me to manage to implement the Acrylic effect you see today.

I haven't, in my casual use, observed the bug you stated. I will keep an eye on that. I am willing to improve and fix the program if I'm not so busy right now.

Centering on startup or with hotkeys, however, are not what this program means to do. The mechanic would be totally different and require a rewrite for this function as well.
